=encoding utf8

=head1 NAME

munin - Munin manpage hub

=head1 DESCRIPTION

Munin is a group of programs to gather data from hosts, graph them,
create html-pages, and optionally warn contacts about any off-limit
values.

The Munin master contains the following programs:
 munin-update - to gather data from machines running munin-node.
 munin-graph  - to create graphs from data contained in rrd-files.
 munin-limits - to check for any off-limit values.
 munin-html   - to draw html-pages on an Munin installation
 munin-cron   - to batch other munin programs

=head1 SEE ALSO

For more information, see the man pages of the individual 
programs L<munin-update(8)>, L<munin-graph(8)>, L<munin-limits(8)>, L<munin-html(8)>, L<munin-cron(8)> or the Munin homepage L<http://munin-monitoring.org/>.

=head1 AUTHORS

Jimmy Olsen, Audun Ytterdal, Brian de Wolf, Nicolai Langfeldt

=head1 COPYRIGHT

Copyright (C) 2002-2008 Audun Ytterdal, Jimmy Olsen, Nicolai
Langfeldt, Linpro AS and others.

This is free software; see the source for copying conditions. There is
NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.

This program is released under the GNU General Public License

=cut
