#! /usr/bin/perl
# $Id$

use strict;
use warnings;
use Data::Dumper;
use Storable;

use Munin::Master::Utils;

while (my $file = shift) {
	my $config = munin_readconfig($file);
	Storable::store_fd($config, \*STDOUT);
}
