#! /usr/bin/perl
# Automatically enables "strict", "warnings", "utf8" and
# Perl 5.10 features

use Mojolicious::Lite;
use DBI;

use Munin::Common::Defaults;

my $datafilename = "$Munin::Common::Defaults::MUNIN_DBDIR/datafile.sqlite";

get '/nodes' => sub {
	my $self = shift;

	# Always reopen the DB since it could have changed since last time
	my $dbh = DBI->connect("dbi:SQLite:dbname=$datafilename","","") or die $DBI::errstr;

	my $nodes = $dbh->selectall_arrayref(
		"SELECT * FROM node",
		{ Slice => {} }, # Each row is stored as a hashref
	);

	$self->respond_to(
		json => {json => $nodes},
		xml  => {xml => $nodes},
		any  => {xml => $nodes},
	);
};

# Start the Mojolicious command system
app->start;
