#! /bin/sh
# Per popular demand : Dirty hack to have a multiple process munin-graph
#
# You shall adapt it to your needs. Notice that it uses GNU's -P xargs
# extension.

NUM_PROCESS=5
MAX_ARGS=10

cat /var/lib/munin/graphs | \
	xargs -P ${NUM_PROCESS} -n ${MAX_ARGS} /usr/share/munin/munin-graph "$@"
