#!/bin/sh
#
# Monkeywrench plugin that just exits on autoconf
#
#%# family=auto
#%# capabilities=autoconf suggest

case $1 in
    autoconf)
	exit 0
	;;
    suggest)
        # This should not be called
        echo "huh?"
	exit 0
	;;
esac
