#!/bin/sh
#
# Monkeywrench plugin that returns a empty suggest list
#
#%# family=auto
#%# capabilities=autoconf suggest

case $1 in
    autoconf)
        echo yes
	exit 0
	;;
    suggest)
        exit 0
	;;
esac
