#!/bin/sh
#
# Monkeywrench plugin that just produces a error
#
#%# family=auto
#%# capabilities=autoconf suggest

case $1 in
    autoconf)
        echo yes
	exit 0
	;;
    suggest)
        echo 'Monkeywrench!' >&2
        exit 255
	;;
esac
