#!/bin/sh

# This test runs "munin-cron" once, connects to the default configured node
# (localhost), and runs through munin-update, munin-graph, munin-limits and
# munin-html.

set -e

su - munin -s /bin/sh -c '/usr/share/munin/munin-update 2>/dev/null' && echo "munin-update OK"
su - munin -s /bin/sh -c '/usr/share/munin/munin-limits 2>/dev/null' && echo "munin-limits OK"
su - munin -s /bin/sh -c '/usr/share/munin/munin-graph 2>/dev/null'  && echo "munin-graph OK"
su - munin -s /bin/sh -c '/usr/share/munin/munin-html 2>/dev/null'   && echo "munin-html OK"
