# This file overrides variables used by the makefile, so it's behaviour
# becomes suitable for building Debian packages.

PREFIX     = $(DESTDIR)/usr
CONFDIR    = $(DESTDIR)/etc/munin
HTMLDIR    = $(DESTDIR)/var/www/munin
DBDIR      = $(DESTDIR)/var/lib/munin

LIBDIR     = $(PREFIX)/share/munin

HOSTNAME   = localhost.localdomain

PERLLIB    = $(DESTDIR)$(shell $(PERL) -V:sitelib | cut -d= -f2 | sed "s/[\';]//g")

CHECKUSER  = \#
CHECKGROUP = \#
CHOWN      = \#
CHMOD      = \#
CHGRP      = \#
