#!/bin/bash

FINDBIN=$(cd -- "$(dirname "$0")" && pwd)
. $FINDBIN/common.sh

cd $BASEDIR


usage() {
    echo "Usage: $0 <NAME>"
    exit 1
}


if [ -z "$1" ]; then
    usage
fi


RUN=$(find $FINDDIR -name $1 -type f -perm -a-rx)
shift

if [ -z "$RUN" ]; then
    usage
fi

URL=$1
shift

PATH_INFO=${URL%%\?*}
QUERY_STRING=${URL##*\?}

export PERL5LIB=$DESTDIR$PERLSITELIB:$PERL5LIB

export PATH_INFO QUERY_STRING
$TIMING $RUN "$@"
