#!/bin/bash

FINDBIN=$(cd -- "$(dirname "$0")" && pwd)
. $FINDBIN/common.sh

cd $BASEDIR

perl -pi -e "s/^tls .*/tls disabled/" $DESTDIR/etc/opt/munin/munin-node.conf
perl -pi -e "s/^tls .*/tls disabled/" $DESTDIR/etc/opt/munin/munin.conf
