#!/bin/sh

FINDBIN=$(cd -- "$(dirname "$0")" && pwd)
. "$FINDBIN/common.sh"

perl -pi -e "s/^tls .*/tls disabled/" "$DESTDIR/etc/opt/munin/munin-node.conf"
perl -pi -e "s/^tls .*/tls disabled/" "$DESTDIR/etc/opt/munin/munin.conf"
