#! /bin/sh

set -e
set -u

FINDBIN=$(cd -- "$(dirname "$0")" && pwd)
. "${FINDBIN}/common.sh"

sqlite3  "${SANDBOX}/var/lib/datafile.sqlite" '.dump' > "${SANDBOX}/var/lib/datafile.sql"
echo "${SANDBOX}/var/lib/datafile.sql"
