#!/bin/sh

set -e
set -u

FINDBIN=$(cd -- "$(dirname "$0")" && pwd)
. "${FINDBIN}/common.sh"

perl -pi -e "s/^tls .*/tls paranoid/" "${CONFDIR}/munin-node.conf"
perl -pi -e "s/^tls .*/tls paranoid/" "${CONFDIR}/munin.conf"
