#! /bin/sh

set -x

PERL_LIB_MUNIN=$(find sandbox -type d -name Munin)
MUNIN_HTTP=$(find sandbox -type f -name munin-httpd)

echo "#! /usr/bin/perl" > $MUNIN_HTTP
cat master/_bin/munin-httpd.in >> $MUNIN_HTTP

chmod -R u+w $PERL_LIB_MUNIN/Master
cp -v master/lib/Munin/Master/* $PERL_LIB_MUNIN/Master
