#!/bin/bash

cat <<EOF

This script is currently broken.

do "perl Build.PL" to configure. "make", "make test" and "make install" in the meantime.

Use "perldoc Build.PL" for options

EOF

exit 0


fakeroot()
{
	# We don't care about permission in dev_script files
	"$@"
}

banner()
{
	echo *************************************************
	echo * "$@"
	echo *************************************************
}



FINDBIN=$(cd -- "$(dirname "$0")" && pwd)
. $FINDBIN/common.sh

cd $BASEDIR

if [ "$1" = "clean" ]; then
	banner CLEAN
	./dev_scripts/stop_munin-node
	./dev_scripts/stop_munin-sched

	rm -rf sandbox
	mkdir sandbox
	make clean || exit
fi

banner BUILD

# Avoiding the real CHOWN (/bin/true)
make CHOWN=true DESTDIR=$DESTDIR HTMLDIR=$DESTDIR/www/munin || exit
make install DESTDIR=$DESTDIR HTMLDIR=$DESTDIR/www/munin CHOWN=true USER=$(id -un) GROUP=$(id -gn) PLUGINUSER=$(id -un) CGIUSER=$(id -un) || exit

# This is to have a local dev node.
# Usually it is much more practical to install the real one, and use it
if [ "$1" = "node" ]; then
    banner INSTALL NODE
    fakeroot make install-plugins-prime DESTDIR=$DESTDIR HTMLDIR=$DESTDIR/www/munin CHOWN=true USER=$(shell id -un) GROUP=$(shell id -gn) PLUGINUSER=$(shell id -un) CGIUSER=$(shell id -un) || exit
    banner CONFIGURE NODE
    perl -pi -e "s/port 4949/port 4948/; 
                 s/user root/user $USER/; 
                 s/group root/group $GROUPS/;
                 s|^(port .*)|\$1

tls disabled
tls_private_key $BASEDIR/common/t/tls/node_key.pem
tls_certificate $BASEDIR/common/t/tls/node_cert.pem
tls_ca_certificate $BASEDIR/common/t/tls/CA/ca_cert.pem
tls_verify_certificate yes
tls_verify_depth 5
|; " $DESTDIR/etc/opt/munin/munin-node.conf

    perl -pi -e "s/(address 127\.0\.0\.1)/\$1\n    port 4948/;
                 s|(# a simple host tree)|tls disabled
tls_private_key $BASEDIR/common/t/tls/master_key.pem
tls_certificate $BASEDIR/common/t/tls/master_cert.pem
tls_ca_certificate $BASEDIR/common/t/tls/CA/ca_cert.pem
tls_verify_certificate yes
tls_verify_depth 5

\$1|" $DESTDIR/etc/opt/munin/munin.conf

    banner CONFIGURE PLUGINS
    ./dev_scripts/run munin-node-configure --shell --families=contrib,auto | sh -x
fi
