#!/bin/sh

set -e
set -u

FINDBIN=$(cd -- "$(dirname "$0")" && pwd)
. "${FINDBIN}/common.sh"

banner() {
	echo "*************************************************"
	echo "* " "$@"
	echo "*************************************************"
}

clean_sandbox() {
	banner CLEAN

	rm -rf sandbox

	./Build distclean
}

make_sandbox() {
	banner BUILD
	perl Build.PL --install_base "${BASEDIR}/sandbox" --debug
	./Build install

	xargs mkdir -p -v <<EOF
		sandbox/etc/munin-conf.d
		sandbox/etc/plugin-conf.d
		sandbox/etc/plugins
		sandbox/var/log
		sandbox/var/lib
		sandbox/var/run
		sandbox/var/spool
EOF
}

configure_plugins() {
	banner CONFIGURE PLUGINS
	munin-node-configure --suggest --shell --families=contrib,auto | sh -x
}

configure_node() {
	banner CONFIGURE NODE
	install -m 0644 "${CONFDIR}/munin-node.conf.sample" "${CONFDIR}/munin-node.conf"

	perl -pi -e "s/port 4949/port ${MUNIN_NODE_PORT}/;
				 s/user root/user $USER/;
				 s/group root/group $GROUP/;
				 s|^(port .*)|\$1

tls disabled
tls_private_key $BASEDIR/t/tls/node_key.pem
tls_certificate $BASEDIR/t/tls/node_cert.pem
tls_ca_certificate $BASEDIR/t/tls/CA/ca_cert.pem
tls_verify_certificate yes
tls_verify_depth 5
|; " "${CONFDIR}/munin-node.conf"

}

configure_master() {
	banner CONFIGURE MASTER

        cat > "${CONFDIR}/munin.conf" <<EOF
# Sandbox munin.conf

tls                    disabled
tls_private_key        $BASEDIR/t/tls/master_key.pem
tls_certificate        $BASEDIR/t/tls/master_cert.pem
tls_ca_certificate     $BASEDIR/t/tls/CA/ca_cert.pem
tls_verify_certificate yes
tls_verify_depth       5

# Read node definitions and other configuration
includedir ${CONFDIR}/munin-conf.d
EOF

        cat > "${CONFDIR}/munin-conf.d/node.ipv4.sandbox.local.conf" <<EOF
# Sandbox munin node definition
[ipv4.sandbox.local]
address 127.0.0.1
port    $MUNIN_NODE_PORT
EOF

        cat > "${CONFDIR}/munin-conf.d/node.ipv6.sandbox.local.conf" <<EOF
# Sandbox munin node definition
[ipv6.sandbox.local]
address [::1]
port    $MUNIN_NODE_PORT
EOF

}

stop_node() {
	./dev_scripts/stop_munin-node
}

case ${1:-} in
	clean)
		stop_node
		clean_sandbox
		;;
	node)
		make_sandbox
		configure_node
		configure_plugins
		configure_master
		;;
	*)
		make_sandbox
		;;
esac
