#!/bin/bash

set -e
set -u

FINDBIN=$(cd -- "$(dirname "$0")" && pwd)
. "${FINDBIN}/common.sh"

cd "$BASEDIR"

usage() {
	echo "Usage: $0 <NAME>"
	exit 1
}

if [ -z "$1" ]; then
	usage
fi

command=$(command -v "$1")
echo "Found: ${command}"
echo "Command line: " "$@"
exec "$@"
