#!/bin/bash

set -e
set -u

FINDBIN=$(cd -- "$(dirname "$0")" && pwd)
. "${FINDBIN}/common.sh"

echo "Starting munin-node"
./dev_scripts/run munin-node

echo ""
echo "**************************************************"
echo "* Listening to "
echo "* ${SANDBOX}/var/log/munin-node.log"
echo "* ..."
echo "**************************************************"
echo ""
tail -f "${SANDBOX}/var/log/munin-node.log"
