#!/bin/sh

set -e
set -u

FINDBIN=$(cd -- "$(dirname "$0")" && pwd)
. "${FINDBIN}/common.sh"


if [ -f "${RUNDIR}/munin-sched.pid" ]; then
	echo "Pid file found. Not starting"
else
	./dev_scripts/run munin-sched "$@"
fi

tail -f "${SANDBOX}/var/log/munin-sched.log"
