#!/bin/bash

set -e
set -u

FINDBIN=$(cd -- "$(dirname "$0")" && pwd)
. "${FINDBIN}/common.sh"

echo "Stopping munin-sched"
if [ -f "${RUNDIR}/munin-sched.pid" ]; then
	xargs -n 1 -r kill < "${RUNDIR}/munin-sched.pid"
else
	echo "Pid file not found. Not stopping"
fi
