#!/bin/sh

set -e
set -u

FINDBIN=$(cd -- "$(dirname "$0")" && pwd)
. "${FINDBIN}/common.sh"

echo "Stopping munin-node"
if [ -f "${RUNDIR}/munin-node.pid" ]; then
	xargs -n 1 -r kill < "${RUNDIR}/munin-node.pid"
else
	echo "Pid file not found. Not stopping"
fi
