#!/bin/bash

FINDBIN=$(cd -- "$(dirname "$0")" && pwd)
. $FINDBIN/common.sh

cd $BASEDIR


if [ -f $DESTDIR/var/run/munin/munin-node.pid ]; then
    cat $DESTDIR/var/run/munin/munin-node.pid | xargs kill
else 
    echo "Pid file not found. Not stopping"
fi

