#!/bin/sh

FINDBIN=$(cd -- "$(dirname "$0")" && pwd)
. "$FINDBIN/common.sh"


if [ -f "$DESTDIR/var/run/munin/munin-sched.pid" ]; then
    xargs kill <"$DESTDIR/var/run/munin/munin-sched.pid"
else 
    echo "Pid file not found. Not stopping"
fi
