#!/bin/sh

: <<EOF

=head1 NAME

foldingathome_wu - Plugin to graph the number of working units
submitted to folding@home

=head1 CONFIGURATION

No configuration

=head1 AUTHORS

Unknown author

=head1 LICENSE

GPLv2

=head1 BUGS

Plugin has capabilities "autoconf", but "autoconf" seems broken.

=head1 MAGIC MARKERS

 #%# family=contrib
 #%# capabilities=autoconf

=cut

EOF

statefile=$MUNIN_PLUGSTATE/plugin-fah_wu.state

if [ "$1" = "autoconf" ]; then
    # Didn't check anything, which is meaningless in this case.
    # echo yes
    echo no
    exit 0
fi

if [ "$1" = "config" ]; then

    echo 'graph_title Folding@Home Working Units submited'
    echo 'graph_args -l 0 --base 1000'
    echo 'graph_category htc'
    echo 'graph_vlabel WU done'
    echo 'wu.label WU'
    echo 'wu.type GAUGE'
    exit 0
fi

wu=$(wget "http://vspx27.stanford.edu/cgi-bin/main.py?qtype=userpage&username=8d" -q -t 1 -T 5 -O - | egrep -A 2 "<TD> WU</TD>" | grep "<b>" | sed 's/.*<b> \([0-9]*\) .*/\1/')

if [ "$wu" = "" ]; then
	if [ -f $statefile ]; then
		echo wu.value `cat $statefile`
	fi
else
	echo $wu > $statefile
	echo wu.value $wu
fi

