#!/bin/sh

##%# family=auto

#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
    if [ -r /usr/bin/icingacli ]; then
        echo yes
        exit 0
    else
        echo "no (could not found icingacli)"
        exit 1
    fi
fi

export TERM=vt100

if [ "$1" = "config" ]; then

    echo "graph_title Icinga Services"
    echo 'graph_args --base 1000'
    echo 'graph_vlabel Count'
    echo 'graph_category icinga'
   
    echo "ok.label Ok"
    echo "warning.label Warning"
    echo "critical.label Critical"
    echo "unknown.label Unknown"
    echo "pending.label Pending"
    
    echo "ok.draw AREA"
    echo "warning.draw STACK"
    echo "critical.draw STACK"
    echo "unknown.draw STACK"
    echo "pending.draw STACK"

    exit
fi

output=$(icingacli monitoring list services)

service_ok=$(echo -e "$output"   | egrep  "├|└" | egrep  "^   OK "| wc -l  )
service_warn=$(echo -e "$output" | egrep  "├|└" | egrep  "^   WARN "| wc -l  )
service_crit=$(echo -e "$output" | egrep  "├|└" | egrep  "^   CRIT "| wc -l  )
service_pend=$(echo -e "$output" | egrep  "├|└" | egrep  "^   PEND "| wc -l  )
service_unkn=$(echo -e "$output" | egrep  "├|└" | egrep  "^   UNKN "| wc -l  )


echo "ok.value $service_ok"
echo "warning.value $service_warn"
echo "critical.value $service_crit"
echo "unknown.value $service_unkn"
echo "pending.value $service_pend"
