#!/bin/sh

: << =cut

=head1 NAME

jenkins_builds - Plugin to measure number of jenkins builds

=head1 CONFIGURATION

[jenkins_builds]
env.jenkins_update_interval 15

jenkins_update_interval: minimum number of minutes between successive
    update operations (adjust according to your resource limits)
    Default: 15

=head1 AUTHOR

Contributed by Holger Levsen. I wrote and used them first for
https://jenkins.debian.net and very much like to hear about
other users of these plugins! Please do tell me!

Use at your own risk and monitor the resource usage of the plugins
too - it will vary depending on your setup!

Patches, postcards and pancakes are all very much welcome!

=head1 LICENSE

Copyright 2012-2014 Holger Levsen <holger@layer-acht.org>

Released under the GPLv2.

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

# shellcheck disable=SC1090
. "$MUNIN_LIBDIR/plugins/plugin.sh"

jenkins_update_interval=${jenkins_update_interval:-15}


if [ "${1:-}" = "autoconf" ]; then
	if [ -d /var/lib/jenkins/jobs ]; then
		echo yes
	else
		echo "no (/var/lib/jenkins/jobs not found)"
	fi
	exit 0
fi

STATEFILE=$MUNIN_PLUGSTATE/$(basename "$0")

# delete statefile if it's older than ${jenkins_update_interval} set in /etc/munin/plugin-conf.d/jenkins
find "$STATEFILE" -maxdepth 0 -mmin "+$jenkins_update_interval" -delete 2>&1 || true

# Does the state file exist and is not outdated?
# In this case just output its data and do not update the state.
if [ -f "$STATEFILE" ] && [ -z "${1:-}" ]; then
	cat "$STATEFILE"
	exit 0
fi

JOB_PREFIXES=$(find "/var/lib/jenkins/jobs/" -maxdepth 1 -mindepth 1 -print0 \
	| xargs -0 -r -n 1 basename | cut -d "_" -f 1 | sort -f -u)
if [ "${1:-}" = "config" ]; then
	echo 'graph_title Jenkins Builds in the last 24h'
	echo 'graph_args --base 1000 -l 0 '
	echo 'graph_scale no'
	echo 'graph_total total'
	echo 'graph_vlabel Jenkins Builds per category in the last 24h'
	echo 'graph_category devel'
	for PREFIX in $JOB_PREFIXES; do
		echo "jenkins_builds_$PREFIX.label $PREFIX builds"
		echo "jenkins_builds_$PREFIX.draw AREASTACK"
	done
	exit 0
fi

for PREFIX in $JOB_PREFIXES; do
	NR=$(find /var/lib/jenkins/jobs/"$PREFIX"*/builds/ -type d -mtime -1 -name "*_*"| wc -l)
	echo "jenkins_builds_$PREFIX.value $NR" | tee -a "$STATEFILE"
done
