#!/usr/bin/perl
#
# Copyright (C) 2010 Magnus Hagander, Redpill Linpro AB
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2 dated June,
# 1991.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301 USA.

=head1 NAME

postgres_prepared_xacts_ - Plugin to monitor number of prepared
                           transactions in PostgreSQL.

=head1 CONFIGURATION

Configuration is done through libpq environment variables, for example
PGUSER, PGDATABASE, etc. For more information, see L<Munin::Plugin::Pgsql>.

To monitor a specific database, link to postgres_prepared_xacts_<databasename>.
To monitor all databases, link to postgres_prepared_xacts_ALL.
To monitor several instances, link to postgres_<tag>_prepared_xacts_<databasename|ALL>
The <tag> can be what you want but without "_". It allows you to define several
database configuration.

Example :
  [postgres_pg91_*]
  env.PGPORT 5432
  [postgres_pg92_*]
  env.PGPORT 5432

=head1 SEE ALSO

L<Munin::Plugin::Pgsql>

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf suggest

=head1 AUTHOR

Magnus Hagander <magnus@hagander.net>, Redpill Linpro AB

=head1 COPYRIGHT/License.

Copyright (c) 2010 Magnus Hagander, Redpill Linpro AB

All rights reserved. This program is free software; you can
redistribute it and/or modify it under the terms of the GNU General
Public License as published by the Free Software Foundation; version 2
dated June, 1991.

=cut

use strict;
use warnings;

use Munin::Plugin::Pgsql;

my $pg = Munin::Plugin::Pgsql->new(
    basename   => 'postgres_[^_]*_?prepared_xacts_',
    title      => 'PostgreSQL prepared transactions',
    info       => 'Number of transactions',
    vlabel     => 'Transactions',
    minversion => '8.1',
    basequery =>
        "SELECT database, count(*) FROM pg_prepared_xacts JOIN pg_database ON datname=database %%FILTER%% GROUP BY database ORDER BY 1",
    wildcardfilter => "WHERE datname=?",
    paramdatabase => 1,
    configquery =>
        "SELECT datname,datname FROM pg_database %%FILTER%% ORDER BY 1",
    suggestquery => "SELECT 'ALL'",
    autoconfquery =>
        "SELECT (setting::integer > 0),'Prepared transactions not enabled' FROM pg_settings WHERE name='max_prepared_transactions'",
    graphdraw => 'AREA',
    stack     => 1,
);

$pg->Process();
exit(0);

