#! /bin/sh

ask() {
    local question default answer

    question=$1
    default=$2
    if [ -z "${PACKAGE_BUILDING}" ]; then
	read -p "${question} [${default}]? " answer
    fi
    if [ x${answer} = x ]; then
	answer=${default}
    fi
    echo ${answer}
}

yesno() {
    local dflt question answer

    question=$1
    dflt=$2
    while :; do
	answer=$(ask "${question}" "${dflt}")
	case "${answer}" in
	[Yy]*)		return 0;;
	[Nn]*)		return 1;;
	esac
	echo "Please answer yes or no."
    done
}

delete_account() {
    local u g home

    u=$1
    g=$2
    if yesno "Do you want me to remove group \"${g}\"" y; then
	pw groupdel -n ${g}
	echo "Done."
    fi
    if yesno "Do you want me to remove user \"${u}\"" y; then
	eval home=~${u}
	pw userdel -n ${u} -r
	echo "Done."
	if [ -d "${home}" ]; then
	    echo "Please remember to remove the home directory \"${home}\""
	fi
    fi
}

delete_crontab_entries() {
    local b e
    b=$1
    e=$2

    TMPFILE=`mktemp -t munin` || exit 1
    crontab -u munin -l | sed -e "/^$b\$/,/^$e\$/d" -e '/^[ 	]*#/d' -e '/^$/d' > $TMPFILE
    if [ -s $TMPFILE ]; then
	crontab -u munin -l | sed -e "/^$b\$/,/^$e\$/d" | crontab -u munin -
	echo "The crontab for user munin had manually created entries."
	echo "Only the automatically created entries have been removed."
	echo "These are the remaining lines:"
	crontab -u munin -l
    else
	crontab -u munin -r
	echo "crontab for user munin removed"
    fi
    rm $TMPFILE
}

case $2 in
    DEINSTALL)
	delete_crontab_entries '#BEGIN_MUNIN' '#END_MUNIN'
	;;
    POST-DEINSTALL)
	delete_account munin munin
	;;
esac
