#!/bin/sh
# 
# Plugin to monitor the load average on a system.
#
# Usage: Link or copy into /etc/munin/node.d/
#
# Magic markers (optional - only used by munin-config and some
# installation scripts):
#
# $Log: load.in,v $
# Revision 1.1.1.1  2006/06/04 20:53:57  he
# Import the client version of the Munin system monitoring/graphing
# tool -- project homepage is at http://munin.sourceforge.net/
#
# This package has added support for NetBSD, via a number of new plugin
# scripts where specific steps needs to be taken to collect information.
#
# I also modified the ntp_ plugin script to make it possible to not
# plot the NTP poll delay, leaving just jitter and offset, which IMO
# produces a more telling graph.
#
#
#
#
#%# family=auto
#%# capabilities=autoconf



# If run with the "autoconf"-parameter, give our opinion on whether we
# should be run on this system or not. This is optional, and only used by
# munin-config. In the case of this plugin, we should most probably
# always be included.

if [ "$1" = "autoconf" ]; then
    if [ -x /sbin/sysctl ]; then
        /sbin/sysctl vm.loadavg > /dev/null
    	if [ $? = "0" ]; then
	    	echo yes
    		exit 0
    	else
	        echo no
		exit 0
	fi
    else
        echo no
        exit 0
    fi
fi

NCPU=`/sbin/sysctl -n hw.ncpu`
# If we fail for some reason, default to 1 cpu
if [ $? != 0 ]; then NCPU=1; fi

# If run with the "config"-parameter, give out information on how the
# graphs should look. 
 
if [ "$1" = "config" ]; then
	# The host name this plugin is for. (Can be overridden to have
	# one machine answer for several)

	# The title of the graph
	echo 'graph_title Load average'
	# Arguments to "rrdtool graph". In this case, tell it that the
	# lower limit of the graph is '0', and that 1k=1000 (not 1024)
	echo 'graph_args --base 1000 -l 0'
	# The Y-axis label
	echo 'graph_vlabel load'
	# We want Cur/Min/Avg/Max unscaled (i.e. 0.42 load instead of
	# 420 milliload)
	echo 'graph_noscale true'
	# The category of the plugin. Defaults to "other".
	echo 'graph_category system'
	# The fields. "label" is used in the legend. "label" is the only
	# required subfield. 
	echo 'load.label load'
	# These two are optional. They are only used if you have
	# configured your munin to tell a Nagios-server about any
	# problems
	echo 'load.warning ' $((10 * $NCPU))
	echo 'load.critical 120'
	# This one is purely to add an explanation to the web page. The first
	# one is for the graph itself, while the second one is for the field
	# "load".
	echo 'graph_info The load average of the machine describes how many processes are in the run-queue (scheduled to run "immediately").'
	echo 'load.info Average load for the five minutes.'

	# Last, if run with the "config"-parameter, quit here (don't
	# display any data)
	exit 0
fi

# If not run with any parameters at all (or only unknown ones), do the
# real work - i.e. display the data. Almost always this will be
# "value" subfield for every data field.

echo -n "load.value "
/sbin/sysctl vm.loadavg | cut -f3 -d' '

# How could this plugin have been written in its simplest form?
# Something like this:
#
# ---------------------
# #!/bin/sh

#
# if [ "$1" = "config" ]; then

# 	echo "graph_title Load average"
#	echo 'graph_args --base 1000 -l 0'
#	echo 'graph_vlabel load'
# 	echo "load.label load"
# 	exit 0
# fi
# echo -n "load.value "
# cut -f1 -d' ' < /proc/loadavg
# ---------------------
#
# Except for the Nagios-warnings (which most people don't have any need
# for) and things used by installation scripts and munin-config (which
# you don't need if you don't plan on submitting your plugin to the
# package), the two versions will work identically.
