#! /bin/sh
# Autobuilding script : SVN -> debian packages
# (c) GPL - Steve Schnepp <steve.schnepp@pwkf.org>

# Has to be launched from the upper svn dir. 
# The dir structure should be like :  
# trunk/
# debian/
# trunk/debian -> ../debian
# packages/

# Stopping on error
set -e

# We don't want localized mesgs
LANG=C

# Always gets the last debian building tools
( cd debian && svn -q up )

[ -d trunk ] || exit 2;

cd trunk

OLDREVISION=$(svn st -v -N . | tr -s ' ' | cut -d' ' -f3 | head -n 1)
[ -z "$NO_UPDATE" ] && svn -q up
REVISION=$(svn st -v -N . | tr -s ' ' | cut -d' ' -f3 | head -n 1)

# Overriding the RELEASE version
echo 1.999.$REVISION > RELEASE

TMPFILE=$(mktemp)

if [ ! -z "$NO_UPDATE" -o $OLDREVISION != $REVISION ]
then
	# Something has changed, building the changelog
	(
		printf "munin (1.999.$REVISION) unstable; urgency=low\n"
		printf "\n" 
		printf "  * Somewhat daily build from trunk\n"
		printf "  * Using a 1.999.SVN naming scheme to enable rpm package building using alien\n";
		printf "  * SVN Log :\n";
		[ -z "$NO_UPDATE" ] && svn log -r$(($OLDREVISION + 1)):$REVISION | perl -lne 'next if m/^---+$/ || m/^$/; s/^/     /; print;'
		printf "\n"
		printf " -- Steve Schnepp <steve.schnepp@gmail.com>  "
		date --rfc-822
		printf "\n"
	) >> $TMPFILE

	# Create a new one	
	( cat debian/changelog >> $TMPFILE ) && cat $TMPFILE > debian/changelog

	# Building....
	mkdir -p ../logs
	( 
		echo $(date) " - START - Building package 1.999.$REVISION"
	 	dpkg-buildpackage -us -uc -F -tc "$@"
		echo $(date) " - STOP - Building package 1.999.$REVISION - retcode : $!"
	) >> ../logs/dpkg-buildpackage-1.999.$REVISION.log 
else 
	exit 1
fi

DEB_ARCH=$(dpkg --print-architecture)
if [ -r "../munin_1.999.${REVISION}_${DEB_ARCH}.changes" ]
then  
	# Moving everything in packages/ and prepare it for upload
	mkdir -p ../packages/munin
	test -r ../packages/override || touch ../packages/override
	cd ../packages
	mv ../*1.999.${REVISION}*.deb munin/
	mv ../*1.999.${REVISION}*.dsc munin/
	mv ../*1.999.${REVISION}*.tar.gz munin/
	mv ../*1.999.${REVISION}*.changes .

	dpkg-scanpackages -m munin override > Packages
	gzip -9 < Packages > Packages.gz
fi

rm $TMPFILE
