# This file overrides variables used by the makefile, so its behaviour
# becomes suitable for building Debian packages.

PREFIX     = $(DESTDIR)/usr
CONFDIR    = $(DESTDIR)/etc/munin
HTMLDIR    = $(DESTDIR)/var/cache/munin/www
DBDIR      = $(DESTDIR)/var/lib/munin
LOGDIR     = $(DESTDIR)/var/log/munin
MANDIR     = $(PREFIX)/share/man

CGIDIR     = $(DESTDIR)/usr/lib/cgi-bin

LIBDIR     = $(PREFIX)/share/munin
JAVALIBDIR = $(DESTDIR)/usr/share/munin

HOSTNAME   = localhost.localdomain

PERLLIB    := $(DESTDIR)$(shell $(PERL) -V:vendorlib | cut -d= -f2 | sed "s/[\';]//g")

JC         = /usr/lib/jvm/default-java/bin/javac
CHECKUSER  = \#
CHECKGROUP = \#
CHOWN      = \#
CHMOD      = \#
CHGRP      = \#

# Distiction between a Linux and FreeBSD kernel
OSTYPE     := $(shell debian/ostype_helper)
