#! /bin/sh

init_plugins() {
    if [ -f /tmp/.munin-node.version ]; then
	prevver=$(cat /tmp/.munin-node.version)
    fi

    if [ -n "$prevver" ]; then
	echo -n "Initializing new plugins.."
	${PKG_PREFIX}/sbin/munin-node-configure --shell --newer "${prevver%-*}" | sh -x
    fi
    echo "done."
}

move_newsyslog_conf() {
    oldfile=${PKG_PREFIX}/etc/newsyslog.conf.d/munin-node
    newfile=${PKG_PREFIX}/etc/newsyslog.conf.d/munin-node.conf
    samplefile=${PKG_PREFIX}/etc/munin/munin-node.newsyslog
    if [ -f ${oldfile} ]; then
	echo "Configuration file found in old location: ${oldfile}"
	if cmp -s ${samplefile} ${newfile} > /dev/null; then
	    echo "Configuration file in new location has not been modified from the default: ${newfile}"
	    echo " => Moving old configuration file to new location"
	    mv -f ${oldfile} ${newfile}
	else
	    echo "Configuration file in new location has been modified from the default: ${newfile}"
	    echo " => Deleting old configuration file"
	    rm ${oldfile}
	fi
    fi
}

########################################################################

case $2 in
    POST-INSTALL)
	if [ -z "${PACKAGE_BUILDING}" ]; then
		init_plugins
	fi
	move_newsyslog_conf
	;;
esac
