#!/usr/bin/perl -T


use strict;
use warnings;

use Getopt::Long;

use Munin::Master::Static::Graph;

my $jobs = 0;
my $destination = "/tmp";

print_usage_and_exit()
  unless GetOptions(
    "jobs|j=i"  => \$jobs,
    "destination|d=s"  => \$destination,
    "version" => \&print_version_and_exit,
    "help"    => \&print_usage_and_exit,
  );

Munin::Master::Static::Graph::create($jobs, $destination);


sub print_usage_and_exit {
    require Pod::Usage;
    Pod::Usage::pod2usage( -verbose => 1 );
}

sub print_version_and_exit {
    require Pod::Usage;
    Pod::Usage::pod2usage(
        -verbose  => 99,
        -sections => 'VERSION|COPYRIGHT',
        -exit     => 0,
    );
}

__END__

=head1 NAME

munin-graph - Generate a static version of the plugins graphics

=head1 USAGE

munin-graph [options]

=head1 REQUIRED ARGUMENTS

None.

=head1 EXIT STATUS

Non-zero on failure.

=head1 DESCRIPTION

munin-graph is a simple generator of the plugins graphics.
It doesn't support zooming, but does support multi-process execution, via forking.

=head1 OPTIONS

=over 5

=item B<< --jobs <number of jobs> >>

This is the number of workers jobs to launch.
Default is 0, meaning no fork is done.

=item B<< --destination <destination directory> >>

Default is "/tmp".

=item B<--help >

View this help message.

=item B<--version >

Show version information.

=back

=head1 VERSION

This is munin-graph (munin) v@@VERSION@@

=head1 AUTHOR

Steve Schnepp

=head1 BUGS AND LIMITATIONS

None known. If you found one, please report under L<https://github.com/munin-monitoring/munin/issues>.

=head1 LICENSE AND COPYRIGHT

Copyright (C) 2023 Steve Schnepp

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; version 2 dated June,
1991.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

=cut
