# Build config for testing

# DESTDIR is empty during building, and optionally set to point to
# a shadow tree during make install.

#
# the base of the Munin installation.
# 
PREFIX     = $(PWD)/t/install

# Where Munin keeps its configurations (server.conf, client.conf, ++)
CONFDIR    = $(PREFIX)/etc

# Client only - Where to put RRD files and other intenal data
DBDIR      = $(PREFIX)/var/lib

# Where Munin should place its logs.
LOGDIR     = $(PREFIX)/var/log

# Location of PID files and other statefiles. On the server, must be
# writable by the user "munin".
STATEDIR   = $(PREFIX)/var/run

# Server only - Where to install the perl libraries
PERLLIB    = $(PREFIX)/perl

# User to run munin as
USER       = nobody
GROUP      = nogroup

# Default user to run the plugins as
PLUGINUSER = nobody

CHECKUSER  = \#
CHECKGROUP = \#
CHOWN      = \#
CHMOD      = \#
CHGRP      = \#
