#!/bin/sh

test_description="request generated html pages"

. debian/tests/sharness.sh


get_munin_url() {
    curl --silent --fail "http://localhost/munin/$1"
}


get_mime_type() {
    file --mime-type --brief -
}


test_expect_success "main site: mime type" '
  [ "$(get_munin_url "/" | get_mime_type)" = "text/xml" ]
'

test_expect_success "main site: dynamically generated" '
  get_munin_url "/" | grep -q "Auto-generated by Munin"
'

test_expect_success "main site: contains node" '
  get_munin_url "/" | grep -q "localhost.localdomain/index.html"
'

test_expect_success "assets: CSS" '
  get_munin_url "/static/style-new.css" | grep -q "margin-top"
'

test_expect_success "node: html" '
  get_munin_url "/localdomain/localhost.localdomain/" | grep -q "df-day.png"
'

test_expect_success "node: graph" '
  get_munin_url "/localdomain/localhost.localdomain/df-day.png" | get_mime_type "image/png"
'

test_done
