#!/bin/sh

# Munin test plugin: autoconf replies yes, but prints
# errors to stdout
#
# #%# family=test
# #%# capabilities=autoconf

do_autoconf()
{
	echo yes
	echo this is an error
	exit 0
}


do_$1 

