#!/bin/sh

# Munin test plugin: 
# 
# suggest offers a list of good suggestions
#
# #%# family=test
# #%# capabilities=autoconf suggest

. t/plugins/default_funcs.sh

do_suggest ()
{
	echo one
	echo two
	echo three
	
	exit 0
}


do_$1

