#!/bin/sh

# Munin test plugin: 
#
# Offers suggestions containing illegal characters
#
# #%# family=test
# #%# capabilities=autoconf suggest

. t/plugins/default_funcs.sh

do_suggest ()
{
	echo one
	echo two
	echo '{}~#)(*&^%$£"!?/'
	exit 0
}


do_$1

