# Modifications from ../../Makefile.config

PREFIX   = $(DESTDIR)/usr
CONFDIR  = $(DESTDIR)/etc/lrrd
LIBDIR   = $(PREFIX)/share/lrrd
SBINDIR  = $(PREFIX)/sbin
BINDIR   = $(PREFIX)/bin
MANDIR   = $(PREFIX)/share/man
HTMLDIR  = $(DESTDIR)/var/www/html/lrrd
DBDIR    = $(DESTDIR)/var/lib/lrrd
LOGDIR   = $(DESTDIR)/var/log/lrrd
STATEDIR = $(DESTDIR)/var/run/lrrd
PERLLIB  = $(DESTDIR)$(shell ( $(PERL) -V:vendorlib | egrep -v "UNKNOWN|=''" || $(PERL) -V:sitelib) | cut -d= -f 2)

# Handled in the lrrd.spec
CHECKUSER:= true
CHECKGROUP:= true
CHOWN   := echo Not done: chown
CHMOD   := echo Not done: chmod
CHGRP   := echo Not done: chgrp
