# Modifications from ../../Makefile.config

PREFIX     = $(DESTDIR)/usr
CONFDIR    = $(DESTDIR)/etc/munin
BINDIR     = $(PREFIX)/bin
SBINDIR    = $(PREFIX)/sbin
MANDIR     = $(PREFIX)/share/man
LIBDIR     = $(PREFIX)/share/munin
HTMLDIR    = $(DESTDIR)/var/www/html/munin
CGIDIR     = $(HTMLDIR)/cgi
DBDIR      = $(DESTDIR)/var/lib/munin
PLUGSTATE  = $(DBDIR)/plugin-state
LOGDIR     = $(DESTDIR)/var/log/munin
STATEDIR   = $(DESTDIR)/var/run/munin
PERL       = $(shell which perl)
PYTHON     = /usr/bin/env python
GOODSH     = $(shell PATH=`getconf PATH` sh -c 'type sh | sed "s/.* //"')
BASH       = /bin/bash
PERLLIB    = $(DESTDIR)$(shell ( $(PERL) -V:vendorlib | egrep -v "UNKNOWN|=''" || $(PERL) -V:sitelib) | cut -d\' -f 2)
OSTYPE     = $(shell uname | tr '[A-Z]' '[a-z]')
HOSTNAME   = $(shell hostname)
MKTEMP     = $(shell ./test-mktemp)
VERSION    = $(shell cat RELEASE)
USER       = munin
GROUP      = munin
PLUGINUSER = nobody
GETENT     = $(shell which getent || which true 2>/dev/null)
CHECKUSER  = $(shell $(GETENT) passwd $(USER) >/dev/null 2>/dev/null || (echo "echo User $(USER) nonexistant. Create the user and retry; exit 2"))
CHECKGROUP = $(shell $(GETENT) group $(GROUP) >/dev/null 2>/dev/null || (echo "echo Group $(GROUP) nonexistant. Create the group and retry; exit 2"))

DOCDIR     = $(PREFIX)/share/doc/munin-$(VERSION)

HASSETR = $(shell perl -e 'use Config; my @vars=("d_setruid", "d_setreuid", "d_setresuid"); foreach my $$var (@vars) { if ($$Config{$$var} eq "define") { print "1\n"; exit 0; } } print "0\n"; exit 0;' )

# Handled in the munin.spec
CHECKUSER:= true
CHECKGROUP:= true
CHOWN   := echo Not done: chown
CHMOD   := echo Not done: chmod
CHGRP   := echo Not done: chgrp
