# Modifications from ../../Makefile.config

PREFIX   = $(DESTDIR)/usr
CONFDIR  = $(DESTDIR)/etc/munin
LIBDIR   = $(PREFIX)/share/munin
SBINDIR  = $(PREFIX)/sbin
BINDIR   = $(PREFIX)/bin
MANDIR   = $(PREFIX)/share/man
HTMLDIR  = $(DESTDIR)/var/www/html/munin
DBDIR    = $(DESTDIR)/var/lib/munin
LOGDIR   = $(DESTDIR)/var/log/munin
STATEDIR = $(DESTDIR)/var/run/munin
PERLLIB  = $(DESTDIR)$(shell ( $(PERL) -V:vendorlib | egrep -v "UNKNOWN|=''" || $(PERL) -V:sitelib) | cut -d\' -f 2)

# Handled in the munin.spec
CHECKUSER:= true
CHECKGROUP:= true
CHOWN   := echo Not done: chown
CHMOD   := echo Not done: chmod
CHGRP   := echo Not done: chgrp
